### PR TITLE
Display Fix Optimization

### PR DESCRIPTION
**Pull request by wuguo138428**
Standardization of theme colors(Use of more standard colors)
Default icon
Optimize "ToastDlg" display
Centered ToastDlg display

### CODE REVIEW

**Comment by SebastianBecker2** [comment]
There seems to be a problem in PowerSchemeSettings.cs in line 95.
The TrayIcon.DefaultIcon is private.
Though I would prefer if the PowerSchemeSettings::GetSetting(Guid) function would take the Resource.power_surge Image directly.
Instead of getting if from TrayIcon.
This should avoid unexpected dependencies.

You should be able to make changes in your local branch and push those to your remote repository. The Pull Request should be updated accordingly.

**Comment by wuguo138428** [comment]
> There seems to be a problem in PowerSchemeSettings.cs in line 95. The TrayIcon.DefaultIcon is private. Though I would prefer if the PowerSchemeSettings::GetSetting(Guid) function would take the Resource.power_surge Image directly. Instead of getting if from TrayIcon. This should avoid unexpected dependencies.
> 
> You should be able to make changes in your local branch and push those to your remote repository. The Pull Request should be updated accordingly.

Fixed 
1. no longer get from "TrayIcon.DefaultIcon.ToBitmap()", but directly.
2. Compatible with the old configuration file to get the default icon code logic.

**Comment by SebastianBecker2** [comment]
I will try to take a look at it at the weekend.

Though I'm a little skeptical about the centered ToastDlg. I deliberately set the position to the task bar.

**Comment by SebastianBecker2** [comment]
I just took a look into the PR. There are a few issues here.
1) You seem to revert a few changes I made. I noticed the PowerSchemeSelectorDlg::SetPositionToTaskbar function which I replaced in the commit cb90b77 in the ToastNotification branch which was merged in the d1b9866 commit.
The weird part is that your repo is up to date. So you had the changes. Did you intend to revert my changes?
2) In PowerSchemeSelectorDlg.cs line 48 and 49 as well as in PowerSchemeSettings.cs line 80 and 95 are commented out code. I know I have left commented out code in the repo as well. Though I try to avoid it as much as I can. Keep in mind that you don't lose deleted code that was previously checked in and pushed. It remains in the git history.
3) In PowerSchemeSelectorDlg.cs line 17 is the member definition PenColor which is unused. Did you intend to use it or can it be deleted? You should get warnings for unused private members. This should help you find situation where you might have forgotten to use or are not used anymore.
4) I haven't actually check how the dialogs look in dark and light theme. But I've noticed you make liberal use of SystemColors. Please keep in mind, those colors are not fixed. For example SystemColors.ButtonShadow might have a different color for High Contrast mode (often used by people with visual impairment) or in future Windows versions. I can't really claim to have paid much attention to that myself. So this isn't a real issue for me. But I wanted to let you know.
5) You set the power_surge icon for Power Schemes that have no settings or have no icon defined. I don't like the way this works. It's not possible for the user to have no icon for any Power Scheme. I intentionally set default icons for the default Power Schemes. But the user always has the option to change or remove the icon. I can certainly live with the idea of having a default icon for non-default Power Schemes. But the user should be able to remove the icon for good. And I would probably prefer a different one than the power_surge icon. But I can change that on my own later.
6) In ToastDlg line 109 is a potential NullReferenceException. Screen.PrimaryScreen is not guaranteed to have a value. It might be null. Not sure how realistic it is though.
7) I just started up and tested the new location of the ToastNotification. I have to say, I'm not feeling good about the centered left side of the primary screen. I kind of expected center bottom or top left or bottom right on the primary screen. But I have never seen an application or an OS for that matter to post notification there. Why do you prefer center left over the alignment with the taskbar?
8) Last point is the 'Optimize "ToastDlg" display' from your initial description. I'm not sure what you meant by 'Optimize'? Are you referring to the changes in the color? Or did I miss something?

I know this is a lot. But as it stands, I can't merge your changes.

**Comment by wuguo138428** [comment]
"ToastDlg" lines 71 through 99 There are three options, which I labeled and explained in the file, and I'm not sure which is better.
"1." the original.
"2." is the main display screen centered, which is what I thought, because that's what my laptop driver animation looks like.
"3." is the system "atl+shift" to switch between languages will pop up the system window, I made it consistent with the system!Z
屏幕截图 2024-06-27 110738
屏幕截图 2024-06-27 110537
屏幕截图 2024-06-27 110649

**Comment by wuguo138428** [comment]
I'll be recreating the "PRs" and uploading the features separately.

**Comment by wuguo138428** [comment]
"Default icon" is added because "PowerSchemeSelectorDlg.cs" is not correct.
I'll try something else.

**Pull request closed without merging**
