### PR TITLE
1.0.8.0_W_ACDC-Switch-LaptopComputer

### PR DESCRIPTION
**Pull request by wuguo138428**

### CODE REVIEW

**Comment by wuguo138428** [comment]
The “PowerACBattery” function is only displayed in the setup screen on the laptop.
Function in “power plans
1.   in “SettingsDlg” there are some window initialization and click event logic “dgvPowerSchemes_CellClick” “SettingsDlg_Load”.
2.  “HandleBtnOkClick” in “SettingsDlg” is used for initialization after saving.
3.  “Program” is used to initialize the “Guid” for startup.
4.  “ProcessMonitor” shares “baselinePowerSchemeGuid” globally in order to realize the correct regulation logic.

**Comment by SebastianBecker2** [comment]
Thank you for the PR. Please give me a few days to check the changes. I'm a bit busy right now.

But I've already seen that github is showing most files as completely changed. I think you might have pushed your changes with CR/LF (Carriage Return / Line Feed) line endings.
Usually with git, the git client will convert line endings to whatever the default for your system is during checkout. So CR/LF for Windows and LF for Linux. And when you commit changes, those line endings will be converted to LF.

This can be configured in the git client you're using. Though I haven't seen anything in Visual Studio to change set. When installing the git command line client on windows, it sets 'core.autocrlf true' in the configuration file. This will do exactly as I described above. If this setting is missing completely, it should use the '* text=auto' setting in the .gitattributes file from the repository.

Sadly I can't tell you exactly how you could change set. If you use the git command line tool, you can set the 'core.autocrlf true' in the configuration. If you're using Visual Studio, it shouldn't have been an issue in the first place. I can't find the option in Visual Studio Code or in SourceTree.

If you can't find a way to fix, it's not too bad. If I checkout your branch, I can see your changes properly in Visual Studio since it fixes the line endings during checkout.
So don't worry too much. I can review your changes perfectly. I just need a few days time.

**Comment by wuguo138428** [comment]
I'm sorry I'm used to Notepad++ not vs problem,,didn't notice this problem,

**Comment by wuguo138428** [comment]
I tried to use vs to synchronize the commit but it didn't work, so I used the github HTML commit again.
I'll try the vs commit again.

**Comment by SebastianBecker2** [comment]
Okay, I checked the PR.
Everything is pretty okay. I like that the checkboxes for AC and Battery are hidden in the SettingsDlg when the system doesn't even have a battery. I wouldn't have thought of that.
I can't really test the code. I don't have a laptop at hand. But I don't see a reason it shouldn't work.

I will rework some of the code. Just to make it look a little nicer. Some reformatting and stuff. But the functionality stays the way you implemented it.
But I will check the other PR before I change anything, to avoid conflicts.

**Pull request merged**
